[tool.poetry]
name = "cavapy"
version = "2.1.0"
description = "CAVA Python package. Retrive climate data."
authors = ["Riccardo Soldan <riccardosoldan@hotmail.it>", "Oleh Lokshyn <olokshyn@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/un-fao/cavapy"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.11"
xclim = "*"
xsdba = "*"
matplotlib = "*"
netcdf4 = "*"
pydap = "*"
dask = "*"
bottleneck = "*"
llvmlite = "*"
cartopy = "*"
seaborn = "*"
tqdm = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
